### PR TITLE
Split API class to constituent classes and incorporate models.py into it.

### PR DESCRIPTION
**Pull request by lasersPew**

### CODE REVIEW

**Review by EMACC99 — CHANGES_REQUESTED** [review]
I see good in this changes and I approve the changes to it. The only thing I will change is the version as I mentioned in the comment is the version number as I consider this changes some usage of the package for certain functions. I think 2.7 will be best

**Comment by lasersPew** [comment]
Doing some more changes in the code to reduce redundancy, making this a draft PR.

**Comment by lasersPew** [comment]
Somehow, rebasing stuff on my end ended up closing this PR, refactoring everything again though I have a copy of my commits

**Comment by EMACC99** [comment]
Sure, if you think some things are ready you can push them as individual PRs to start pushing the changes eventually

**Comment by lasersPew** [comment]
> push them as individual PRs

I would love to, though when I split the API, I kind of add function or change things impulsively. Anyways, I will take a long time as I try different solutions to have the parts in their own parts.

**Pull request closed without merging**
