### PR TITLE
Split API class to constituent classes and incorporate models.py

### PR DESCRIPTION
**Pull request by lasersPew**
Changes
- Fixed the unit test and README.md to match the changes.
- Added .sampleenv and transitioned onto environment variable-based system.
- Bumped the version to 2.7, as stated in #35 
- Added requirements.txt
- Added .idea to gitignore(for JetBrains IDEs)
- Added APIClients endpoint.
- Removed unnecessary errors that can just use ValueError

Summary:
This PR had split the main Manga class from api.py and merged it to models.py. It used composition(and some inheritance where it is needed) to have the module be more cohesive. It changes from `md.get_user_list()` to `md.people.User(auth=auth).get_user_list()`.

I splitted up the API into its constituent group files(files containing multiple subclasses) as it prevents the merge conflicts I recently had(should be the owner's job, but did the expense of refactoring everything) and somehow makes it cohesive though IDK how can I make something like `md.User().get_user_list()`. If someone can suggest changes, I give my gratitude to them. This ain't perfect and I feel like this needs a bit more testing to make sure everything works. 

I just added the APIClients class as it is essential in authentication though I suggest that other added methods(like Report, Statistics, etc.) should be added after this gets merged.

TODO before merging:
- Full package unit test coverage
- Create docstring with Google NumPY format(see auth.py)
- Future: Move the wiki

### CODE REVIEW

**Comment by EMACC99** [comment]
I'm gonna take a more detailed look into it. I looked at the report from the GitHub actions and saw that it passed the tests that didn't require the auth, I'm going to check the ones that need auth locally before merging

**Review by EMACC99 — APPROVED** [review]
I ran the tests and found that one was failing. Investigated it and solved. Everything is in the review, I attach the code coverage results here


```
Name                     Stmts   Miss  Cover   Missing
------------------------------------------------------
mangadex/__init__.py         9      0   100%
mangadex/auth.py           140     87    38%   16-23, 77-78, 88-100, 115-141, 144-146, 149, 152-157, 161-163, 167-171, 182-187, 190-192, 195-200, 203-207, 210-213, 216-220, 223-227, 231-240
mangadex/errors.py          25      9    64%   20-21, 27, 32-34, 39-41
mangadex/people.py         251     73    71%   45, 74-78, 83, 91, 94, 146-156, 177-186, 195-196, 238, 259, 286, 294, 297, 329-331, 347-357, 378-387, 396-397, 417, 420-422, 425, 428, 438, 450-451, 460-464, 467, 479-481, 503-509, 524-528, 562-563
mangadex/series.py         501    124    75%   53, 78-85, 106, 114, 117-123, 142-147, 173-180, 221-227, 238-248, 286, 318, 325, 327, 329, 343-350, 391-402, 426-441, 453-463, 494, 531, 534, 584, 596-597, 624-625, 627-628, 633-634, 639-640, 642-643, 645-646, 648-649, 651-652, 654-655, 681, 689, 692-702, 846-856, 873, 914-924, 934-936, 976-980, 1020-1021, 1062, 1092, 1154-1155, 1168-1169, 1194-1201, 1242-1250, 1260-1261
mangadex/url_models.py      83     24    71%   18-20, 50-52, 56-58, 62-74, 94, 116, 119, 121-122
test/test_unittest.py      173      1    99%   296
------------------------------------------------------
TOTAL                     1182    318    73%
```

**Comment by lasersPew** [comment]
> I ran the tests and found that one was failing. Investigated it and solved. Everything is in the review, I attach the code coverage results here
> 
> ```
> Name                     Stmts   Miss  Cover   Missing
> ------------------------------------------------------
> mangadex/__init__.py         9      0   100%
> mangadex/auth.py           140     87    38%   16-23, 77-78, 88-100, 115-141, 144-146, 149, 152-157, 161-163, 167-171, 182-187, 190-192, 195-200, 203-207, 210-213, 216-220, 223-227, 231-240
> mangadex/errors.py          25      9    64%   20-21, 27, 32-34, 39-41
> mangadex/people.py         251     73    71%   45, 74-78, 83, 91, 94, 146-156, 177-186, 195-196, 238, 259, 286, 294, 297, 329-331, 347-357, 378-387, 396-397, 417, 420-422, 425, 428, 438, 450-451, 460-464, 467, 479-481, 503-509, 524-528, 562-563
> mangadex/series.py         501    124    75%   53, 78-85, 106, 114, 117-123, 142-147, 173-180, 221-227, 238-248, 286, 318, 325, 327, 329, 343-350, 391-402, 426-441, 453-463, 494, 531, 534, 584, 596-597, 624-625, 627-628, 633-634, 639-640, 642-643, 645-646, 648-649, 651-652, 654-655, 681, 689, 692-702, 846-856, 873, 914-924, 934-936, 976-980, 1020-1021, 1062, 1092, 1154-1155, 1168-1169, 1194-1201, 1242-1250, 1260-1261
> mangadex/url_models.py      83     24    71%   18-20, 50-52, 56-58, 62-74, 94, 116, 119, 121-122
> test/test_unittest.py      173      1    99%   296
> ------------------------------------------------------
> TOTAL                     1182    318    73%
> ```

Care to explain what this is? I'm relatively new to package creation since I focus on Data Analysis stuff. Sorry.

**Review by EMACC99 — APPROVED** [review]

**Comment by EMACC99** [comment]
Hey @lasersPew I saw your changes and that you added the ping function, I saw that it wasn't configured correctly and fix it, also it helped to see there where other parts of the code that where missing some things (like what happens when the response is not a json like when you're doing a ping :) ). I'm gonna merge this now so that everyone gets to enjoy the new changes and will continue to submit improvements thru a dev branch

**Pull request merged**
